[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache-foundry'
via_ir = true
auto_detect_solc = true
build_info = true
extra_output = ["storageLayout"]
solc = "0.8.20"
