[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'foundry/test'
cache_path = 'foundry/cache'
via_ir = true
auto_detect_solc = true
build_info = true
extra_output = ["storageLayout"]
