apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-api
  namespace: governance-api
  labels:
    "app.kubernetes.io/name": "governance-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": "governance-api"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "governance-api"
    spec:
      containers:
        - image: governance-api
          name: governance-api
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 300Mi
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: governance-api
                  key: NODE_ENV
            - name: PINATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: governance-api
                  key: PINATA_API_KEY
            - name: PINATA_SECRET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: governance-api
                  key: PINATA_SECRET_API_KEY
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: governance-api
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: governance-api
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: governance-api
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: governance-api
                  key: POSTGRES_USER
