apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: governance-api
  namespace: governance-api
  labels:
    app.kubernetes.io/name: "governance-api"
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        requestPath: /api
        port: 3000
  targetRef:
    group: ""
    kind: Service
    name: governance-api
