apiVersion: v1
kind: Service
metadata:
  name: governance-api
  namespace: governance-api
  labels:
    "app.kubernetes.io/name": "governance-api"
  annotations:
    cloud.google.com/backend-config: '{"default": "governance-api"}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    "app.kubernetes.io/name": "governance-api"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: governance-api
spec:
  healthCheck:
    requestPath: /api
