version: '3'

networks:
  zilliqa:

services:
  #isolatedserver
  isolatedserver:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: isolatedserver
    #    restart: always
    volumes:
    - ./logs:/zilliqa/logs
    ports:
    - "5555:5555"
    networks:
      - zilliqa

  isolatedserver_faucet:
    build: 
      context: ./faucet
      dockerfile: Dockerfile
    container_name: isolatedserver_faucet
    #    restart: always
    ports:
    - "5556:5556"
    networks:
      - zilliqa
    links:
      - isolatedserver