apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: devex-apollo
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: devex-apollo.zilstg.dev
      - op: replace
        path: "/spec/rules/1/host"
        value: stg-devex-apollo.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: devex-apollo-zilstg-dev
          networking.gke.io/managed-certificates: devex-apollo
          networking.gke.io/v1beta1.FrontendConfig: devex-apollo
  - target:
      kind: Deployment
      name: devex-apollo
    patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/resources/limits/memory"
        value: 1000Mi

patchesStrategicMerge:
  - configmap.yaml
  - secrets-app.yaml

namespace: devex-apollo-staging
