apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: faucet-service
  labels:
    app.kubernetes.io/name: faucet-service
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: RESPONSE_CODE
