/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CollectorInterface extends Interface {
  getFunction(nameOrSignature: "echo"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Echoed"): EventFragment;

  encodeFunctionData(
    functionFragment: "echo",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "echo", data: BytesLike): Result;
}

export namespace EchoedEvent {
  export type InputTuple = [hash: BytesLike, signature: BytesLike];
  export type OutputTuple = [hash: string, signature: string];
  export interface OutputObject {
    hash: string;
    signature: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Collector extends BaseContract {
  connect(runner?: ContractRunner | null): Collector;
  waitForDeployment(): Promise<this>;

  interface: CollectorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  echo: TypedContractMethod<
    [hash: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "echo"
  ): TypedContractMethod<
    [hash: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Echoed"
  ): TypedContractEvent<
    EchoedEvent.InputTuple,
    EchoedEvent.OutputTuple,
    EchoedEvent.OutputObject
  >;

  filters: {
    "Echoed(bytes32,bytes)": TypedContractEvent<
      EchoedEvent.InputTuple,
      EchoedEvent.OutputTuple,
      EchoedEvent.OutputObject
    >;
    Echoed: TypedContractEvent<
      EchoedEvent.InputTuple,
      EchoedEvent.OutputTuple,
      EchoedEvent.OutputObject
    >;
  };
}
