/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20BridgeSol from "./ERC20Bridge.sol";
export type { erc20BridgeSol };
import type * as testSol from "./Test.sol";
export type { testSol };
export type { Bridged } from "./Bridged";
export type { Collector } from "./Collector";
export type { Relayer } from "./Relayer";
export type { ValidatorManager } from "./ValidatorManager";
