apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: zillion
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: stake.zilliqa.com
      - op: remove
        path: "/spec/rules/2"
      - op: remove
        path: "/spec/rules/1"
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: stake-zilliqa-com
          networking.gke.io/managed-certificates: zillion
          networking.gke.io/v1beta1.FrontendConfig: zillion
  - target:
      kind: ConfigMap
      name: zillion-config
    patch: |-
      - op: replace
        path: "/data/config.js"
        value: |
          window['config'] = {
              networks_config: {
                  testnet: {
                      proxy: "",
                      impl: "",
                      blockchain: "https://dev-api.zilliqa.com",
                      node_status: "https://testnet-viewer.zilliqa.com",
                      api_list: [
                          "https://bumblebee-api.zilliqa.network",
                          "https://dev-api.zilliqa.com",
                      ]
                  },
                  mainnet: {
                      proxy: "0x62A9d5D611CDCaE8D78005F31635898330e06B93",
                      impl: "0xa7C67D49C82c7dc1B73D231640B2e4d0661D37c1",
                      blockchain: "https://api.zilliqa.com",
                      node_status: "https://staking-viewer.zilliqa.com",
                      api_list : [
                          "https://api.zilliqa.com",
                          "https://ssn-zilliqa.cex.io/api",
                          "https://ssn.ignitedao.io/api",
                          "https://ssn.zillet.io",
                          "https://zil-staking.ezil.me/api",
                          "https://staking-zil.kucoin.com/api",
                      ]
                  },
                  isolated_server: {
                      proxy: "0x0578B8e9D9c2493D4a2E98f364c7ed311F7a0d71",
                      impl: "",
                      blockchain: "https://zilliqa-isolated-server.zilliqa.com",
                      node_status: "",
                      api_list : [
                          "https://zilliqa-isolated-server.zilliqa.com"
                      ]
                  }
              },
              blockchain_explorer_config: "viewblock",
              refresh_rate_config: 300000,
              api_max_retry_attempt: 10,
              environment_config: "prod"
          }

namespace: zillion-prd
