apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: zillion
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: stake.zilliqa.com
      - op: remove
        path: "/spec/rules/2"
      - op: remove
        path: "/spec/rules/1"
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: stake-zilliqa-com
          networking.gke.io/managed-certificates: zillion
          networking.gke.io/v1beta1.FrontendConfig: zillion

namespace: zillion-prd
