language: node_js
sudo: true
jobs:
  include:
    - os: linux
      dist: bionic
      node_js:
        - 12
    - os: linux
      dist: bionic
      node_js:
        - 14
    - os: linux
      dist: bionic
      node_js:
        - 16
    - os: osx
      node_js:
        - 12
    - os: osx
      node_js:
        - 14
    - os: osx
      node_js:
        - 16
branches:
  except:
    - /^v[0-9]/
install:
  - npm install --global yarn
  - yarn install
  - yarn global add webpack
script:
  - yarn bootstrap
  - yarn validate
  - yarn bundle
  - bash tasks/local-registry.sh
  - bash tasks/tsc.sh
  - yarn build:web
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then OS_NAME=macos ; else OS_NAME=$TRAVIS_OS_NAME ; fi
  - curl -Os https://uploader.codecov.io/latest/$OS_NAME/codecov
  - chmod +x codecov
  - ./codecov -t ${CODECOV_TOKEN} -f coverage/coverage-final.json -Z
cache:
  directories:
    - "$HOME/.yarn-cache"
