version: "1"
services:
  node0:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: info
    container_name: validatornode0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./infra/config-leader.toml:/config.toml"
    command:
      - /bridge-validator
      - 65d7f4da9bedc8fb79cbf6722342960bbdfb9759bc0d9e3fb4989e831ccbc227

  node1:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: info
    container_name: validatornode1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./infra/config.toml:/config.toml"
    command:
      - /bridge-validator
      - 62070b1a3b5b30236e43b4f1bfd617e1af7474635558314d46127a708b9d302e

  node2:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: info
    container_name: validatornode2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./infra/config.toml:/config.toml"
    command:
      - /bridge-validator
      - 56d7a450d75c6ba2706ef71da6ca80143ec4971add9c44d7d129a12fa7d3a364

  node3:
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: info
    container_name: validatornode3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./infra/config.toml:/config.toml"
    command:
      - /bridge-validator
      - db670cbff28f4b15297d03fafdab8f5303d68b7591bd59e31eaef215dd0f246a
