apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xbridge-fe-prd

resources:
  - ../../base
  - certificates.yaml
  - backend-config.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: xbridge-frontend
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: xbridge.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: xbridge-zilliqa-com
          networking.gke.io/managed-certificates: xbridge-frontend
          networking.gke.io/v1beta1.FrontendConfig: xbridge-frontend
  - target:
      kind: Service
      name: xbridge-frontend
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          beta.cloud.google.com/backend-config: '{"default": "xbridge-frontend"}'
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: VITE_ENV
          value: "PROD"
    target:
      kind: Deployment
      name: xbridge-frontend
