apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - sealed-secrets.yaml

images:
  - name: devex-apollo
    newName: 816080630680.dkr.ecr.us-west-2.amazonaws.com/devex-apollo
    newTag: ${FULL_VERSION_TAG}

patches:
  - patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: stg-devex-apollo.eks01uws2.stg.z7a.xyz
      - op: replace
        path: "/spec/rules/1/host"
        value: stg-devex-apollo.zilliqa.com
    target:
      kind: Ingress
      name: devex-apollo

namespace: devex-apollo-staging
