apiVersion: v1
kind: Secret
metadata:
  name: faucet-service
  namespace: faucet-service
  labels:
    app.kubernetes.io/name: faucet-service
  annotations:
    zilliqa.com/autofill: prj-p-blockchain-infra
type: Opaque
data:
  AMOUNT_IN_ZIL: "zilliqa-isolated-faucet/AMOUNT_IN_ZIL"
  BATCH_INTERVAL: "zilliqa-isolated-faucet/BATCH_INTERVAL"
  BATCH_LIMIT: "zilliqa-isolated-faucet/BATCH_LIMIT"
  CHAIN_ID: "zilliqa-isolated-faucet/CHAIN_ID"
  ENV_TYPE: "zilliqa-isolated-faucet/ENV_TYPE"
  NODE_URL: "zilliqa-isolated-faucet/NODE_URL"
  PRIVATE_KEY: "zilliqa-isolated-faucet/PRIVATE_KEY"
  RECAPTCHA_SECRET: "zilliqa-isolated-faucet/RECAPTCHA_SECRET"
  TTL: "zilliqa-isolated-faucet/TTL"
