apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zilliqa-isolated-server-stg

resources:
  - ../../base
  - configmap.yaml
  - app-secret.yaml
  - certificate.yaml
  - backend-config.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: zilliqa-isolated-server
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: stg-zilliqa-isolated-server.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: stg-zilliqa-isolated-server-zilliqa-com
          networking.gke.io/managed-certificates: zilliqa-isolated-server
          networking.gke.io/v1beta1.FrontendConfig: zilliqa-isolated-server
  - target:
      kind: Service
      name: zilliqa-isolated-server
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          beta.cloud.google.com/backend-config: '{"default": "zilliqa-isolated-server"}'
