apiVersion: v1
kind: Secret
metadata:
  name: zilliqa-isolated-server
  namespace: zilliqa-isolated-server
  labels:
    app.kubernetes.io/name: zilliqa-isolated-server
  annotations:
    zilliqa.com/autofill: prj-p-prod-apps
type: Opaque
data:
  UUID: "zilliqa-isolated-server/UUID"
