apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: zilliqa-isolated-server
  namespace: zilliqa-isolated-server
  labels:
    app.kubernetes.io/name: zilliqa-isolated-server
spec:
  timeoutSec: 30
  healthCheck:
    requestPath: /
    port: 80
