apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: dev-wallet
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: stg-dev-wallet.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: stg-dev-wallet-zilliqa-com
          networking.gke.io/managed-certificates: dev-wallet
          networking.gke.io/v1beta1.FrontendConfig: dev-wallet

namespace: dev-wallet-stg
