apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - secrets-app.yaml
  - svc.yaml

namespace: devex-apollo
