apiVersion: v1
kind: Secret
metadata:
  name: devex-apollo
  annotations:
    zilliqa.com/autofill: "devex-apollo"
type: Opaque
data:
  DOCUMENTDB_HOST: ""
  DOCUMENTDB_USER: ""
  DOCUMENTDB_PASSWORD: ""
  DOCUMENTDB_DB: ""
