apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: multisig
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: multisig.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: multisig-zilliqa-com
          networking.gke.io/managed-certificates: multisig
          networking.gke.io/v1beta1.FrontendConfig: multisig

namespace: multisig-prd
