/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Collector, CollectorInterface } from "../../contracts/Collector";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ValidatorManager",
        name: "_validatorManager",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "Echoed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "echo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161037338038061037383398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b6102e0806100936000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063274b9f1014610030575b600080fd5b61004361003e36600461014c565b610045565b005b60005460405163199ed7c960e11b81526001600160a01b039091169063333daf9290610077908590859060040161024d565b602060405180830381865afa158015610094573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100b8919061026e565b6100fa5760405162461bcd60e51b815260206004820152600f60248201526e2bb937b733903b30b634b230ba37b960891b604482015260640160405180910390fd5b817f84259fbf8a54adfe7ce845eee74785aacedcf222bdeb9f31672eb2a429d453e08260405161012a9190610297565b60405180910390a25050565b634e487b7160e01b600052604160045260246000fd5b6000806040838503121561015f57600080fd5b82359150602083013567ffffffffffffffff8082111561017e57600080fd5b818501915085601f83011261019257600080fd5b8135818111156101a4576101a4610136565b604051601f8201601f19908116603f011681019083821181831017156101cc576101cc610136565b816040528281528860208487010111156101e557600080fd5b8260208601602083013760006020848301015280955050505050509250929050565b6000815180845260005b8181101561022d57602081850181015186830182015201610211565b506000602082860101526020601f19601f83011685010191505092915050565b8281526040602082015260006102666040830184610207565b949350505050565b60006020828403121561028057600080fd5b8151801515811461029057600080fd5b9392505050565b602081526000610290602083018461020756fea2646970667358221220590ed76b9b397a7dddfb203452fb71d90f8b6fcad5e57c5d3589686e12fd75e164736f6c63430008140033";

type CollectorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CollectorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Collector__factory extends ContractFactory {
  constructor(...args: CollectorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _validatorManager: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_validatorManager, overrides || {});
  }
  override deploy(
    _validatorManager: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_validatorManager, overrides || {}) as Promise<
      Collector & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Collector__factory {
    return super.connect(runner) as Collector__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CollectorInterface {
    return new Interface(_abi) as CollectorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Collector {
    return new Contract(address, _abi, runner) as unknown as Collector;
  }
}
