/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20BridgeSol from "./ERC20Bridge.sol";
export * as testSol from "./Test.sol";
export { Bridged__factory } from "./Bridged__factory";
export { Collector__factory } from "./Collector__factory";
export { Relayer__factory } from "./Relayer__factory";
export { ValidatorManager__factory } from "./ValidatorManager__factory";
