apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml

patches:
  - target:
      kind: Ingress
      name: devex-apollo
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: devex-apollo.zilliqa.com
      - op: remove
        path: "/spec/rules/1"
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: devex-apollo-zilliqa-com
          networking.gke.io/managed-certificates: devex-apollo

patchesStrategicMerge:
  - configmap.yaml
  - secrets-app.yaml

namespace: devex-apollo-prd
