apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
images:
  - name: 298213327629.dkr.ecr.us-west-2.amazonaws.com/developer-explorer
    newTag: ${FULL_VERSION_TAG}
namespace: devel-explorer-prd
