apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
images:
  - name: 298213327629.dkr.ecr.us-west-2.amazonaws.com/developer-explorer
    newTag: ${FULL_VERSION_TAG}

patches:
  - patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: devex-${CUSTOM_VERSION_URI}.eks01uws2.stg.z7a.xyz
    target:
      kind: Ingress
      name: developer-explorer

namespace: devel-explorer-preview-${FULL_VERSION_URI}
