apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: developer-portal-zq2
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: dev-zq2.zilliqa.com
      - op: remove
        path: "/spec/rules/1"
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: dev-zq2-zilliqa-com
          networking.gke.io/managed-certificates: developer-portal-zq2
          networking.gke.io/v1beta1.FrontendConfig: developer-portal-zq2

namespace: developer-portal-zq2-prd
