apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml

patches:
  - target:
      kind: Ingress
      name: pdt
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: pdt.zilstg.dev
      - op: replace
        path: "/spec/rules/1/host"
        value: stg-pdt.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: pdt-zilstg-dev
          networking.gke.io/managed-certificates: pdt

namespace: pdt-staging
