apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - service_account.yaml

namespace: pdt-staging

patches:
  - target:
      kind: Deployment
      name: pdt-cronjob
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/serviceAccountName
        value: pdt
  - target:
      kind: Deployment
      name: pdt-listen
    patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: pdt

patchesStrategicMerge:
  - configmap.yaml
