apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: pdt-staging

patches:
  - target:
      kind: Deployment
      name: pdt
    patch: |-
      - op: add
        path: /spec/template/spec
        value:
          serviceAccountName: pdt
