apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: governance-snapshot
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: stg-governance.zilliqa.com
      - op: replace
        path: "/spec/rules/1/host"
        value: stg-vote.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: stg-governance-zilliqa-com
          networking.gke.io/managed-certificates: governance-snapshot
          networking.gke.io/v1beta1.FrontendConfig: governance-snapshot

namespace: governance-snapshot-stg
