apiVersion: apps/v1
kind: Deployment
metadata:
  name: zilliqa-devportal
  namespace: devportal
  labels:
    "app.kubernetes.io/name": "zilliqa-devportal"
spec:
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": "zilliqa-devportal"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "zilliqa-devportal"
    spec:
      containers:
        - image: zilliqa-devportal
          name: zilliqa-devportal
          ports:
            - containerPort: 80
