apiVersion: v1
kind: Service
metadata:
  name: developer-portal
  namespace: developer-portal
  labels:
    app.kubernetes.io/name: "developer-portal"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "developer-portal"
