load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "expand_workspace_status",
    srcs = ["expand_workspace_status.py"],
    main = "expand_workspace_status.py",
    visibility = ["//visibility:public"],
)
