load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "version-lib-generator",
    srcs = ["version-lib-generator.py"],
    visibility = [
        "//visibility:public",
    ],
)
