apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml

patches:
  - target:
      kind: Ingress
      name: devex
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: devex.zilstg.dev
      - op: replace
        path: "/spec/rules/1/host"
        value: stg-devex.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: devex-zilstg-dev
          networking.gke.io/managed-certificates: devex

namespace: devex-staging
