/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ERC20BridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bridge"
      | "dispatched"
      | "exit"
      | "finish"
      | "initialize"
      | "queried"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Failed" | "Initialized" | "Started" | "Succeeded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bridge",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dispatched",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "exit",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finish",
    values: [boolean, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queried",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dispatched", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "finish", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "queried", data: BytesLike): Result;
}

export namespace FailedEvent {
  export type InputTuple = [arg0: string];
  export type OutputTuple = [arg0: string];
  export interface OutputObject {
    arg0: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StartedEvent {
  export type InputTuple = [
    arg0: AddressLike,
    arg1: AddressLike,
    arg2: BigNumberish
  ];
  export type OutputTuple = [arg0: string, arg1: string, arg2: bigint];
  export interface OutputObject {
    arg0: string;
    arg1: string;
    arg2: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SucceededEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC20Bridge extends BaseContract {
  connect(runner?: ContractRunner | null): ERC20Bridge;
  waitForDeployment(): Promise<this>;

  interface: ERC20BridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bridge: TypedContractMethod<
    [token: AddressLike, owner: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  dispatched: TypedContractMethod<
    [target: AddressLike, call: BytesLike],
    [[boolean, string] & { success: boolean; response: string }],
    "payable"
  >;

  exit: TypedContractMethod<
    [token: AddressLike, owner: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  finish: TypedContractMethod<
    [success: boolean, res: BytesLike, nonce: BigNumberish],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<[relayer: AddressLike], [void], "nonpayable">;

  queried: TypedContractMethod<
    [target: AddressLike, call: BytesLike],
    [[boolean, string] & { success: boolean; response: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bridge"
  ): TypedContractMethod<
    [token: AddressLike, owner: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dispatched"
  ): TypedContractMethod<
    [target: AddressLike, call: BytesLike],
    [[boolean, string] & { success: boolean; response: string }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "exit"
  ): TypedContractMethod<
    [token: AddressLike, owner: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finish"
  ): TypedContractMethod<
    [success: boolean, res: BytesLike, nonce: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "queried"
  ): TypedContractMethod<
    [target: AddressLike, call: BytesLike],
    [[boolean, string] & { success: boolean; response: string }],
    "view"
  >;

  getEvent(
    key: "Failed"
  ): TypedContractEvent<
    FailedEvent.InputTuple,
    FailedEvent.OutputTuple,
    FailedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Started"
  ): TypedContractEvent<
    StartedEvent.InputTuple,
    StartedEvent.OutputTuple,
    StartedEvent.OutputObject
  >;
  getEvent(
    key: "Succeeded"
  ): TypedContractEvent<
    SucceededEvent.InputTuple,
    SucceededEvent.OutputTuple,
    SucceededEvent.OutputObject
  >;

  filters: {
    "Failed(string)": TypedContractEvent<
      FailedEvent.InputTuple,
      FailedEvent.OutputTuple,
      FailedEvent.OutputObject
    >;
    Failed: TypedContractEvent<
      FailedEvent.InputTuple,
      FailedEvent.OutputTuple,
      FailedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Started(address,address,uint256)": TypedContractEvent<
      StartedEvent.InputTuple,
      StartedEvent.OutputTuple,
      StartedEvent.OutputObject
    >;
    Started: TypedContractEvent<
      StartedEvent.InputTuple,
      StartedEvent.OutputTuple,
      StartedEvent.OutputObject
    >;

    "Succeeded()": TypedContractEvent<
      SucceededEvent.InputTuple,
      SucceededEvent.OutputTuple,
      SucceededEvent.OutputObject
    >;
    Succeeded: TypedContractEvent<
      SucceededEvent.InputTuple,
      SucceededEvent.OutputTuple,
      SucceededEvent.OutputObject
    >;
  };
}
