/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BridgedERC20 } from "./BridgedERC20";
export type { ERC20Bridge } from "./ERC20Bridge";
export type { MyToken } from "./MyToken";
