apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml

patches:
  - target:
      kind: Ingress
      name: neo-savant-ide
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: neo-savant-ide.zilstg.dev
      - op: replace
        path: "/spec/rules/1/host"
        value: stg-ide.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: neo-savant-ide-zilstg-dev
          networking.gke.io/managed-certificates: neo-savant-ide

namespace: neo-savant-ide-staging
