apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
images:
  - name: zilliqa-devportal
    newName: 298213327629.dkr.ecr.us-west-2.amazonaws.com/zilliqa-devportal
    newTag: ${FULL_VERSION_TAG}

namespace: devportal-prd
