apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xbridge-fe-stg

resources:
  - ../../base
  - certificates.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: xbridge-frontend
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: xbridge.zilstg.dev
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: xbridge-zilstg-dev
          networking.gke.io/managed-certificates: xbridge-frontend
          networking.gke.io/v1beta1.FrontendConfig: xbridge-frontend
  - target:
      kind: Service
      name: xbridge-frontend
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          beta.cloud.google.com/backend-config: '{"default": "xbridge-frontend"}'
