apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdt-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 128Gi
  storageClassName: standard
  hostPath:
    path: /tmp/pdt-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdt-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: standard
  volumeName: pdt-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdt
  labels:
    "app.kubernetes.io/name": "pdt"
spec:
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": "pdt"
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "pdt"
    spec:
      containers:
        - image: pdt:latest
          name: pdt
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: pdt-pv
              mountPath: /data
      volumes:
        - name: pdt-pv
          persistentVolumeClaim:
            claimName: pdt-pvc
