apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
images:
  - name: zilliqa-devportal
    newName: 298213327629.dkr.ecr.us-west-2.amazonaws.com/zilliqa-devportal
    newTag: ${FULL_VERSION_TAG}

patches:
  - patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: zilliqa-devportal.platform.prd.z7a.xyz
      - op: replace
        path: "/spec/rules/1/host"
        value: dev.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: nginx
    target:
      kind: Ingress
      name: neo-savant-ide

namespace: devportal-prd
