apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: faucet-service
  labels:
    app.kubernetes.io/name: faucet-service
spec:
  timeoutSec: 30
  healthCheck:
    requestPath: /livez
    port: 8080
