site_name: Zilliqa Developer Portal
site_url: https://dev.zilliqa.com
docs_dir: !ENV DOC_SOURCE
site_description: Zilliqa blockchain
site_author: Zilliqa

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/versions.js
  - js/connect.js

nav:
  - News: "index.md"
  - Home: "home.md"
  - "New in ZQ2": "changes.md"
  - "Endpoints": "endpoints.md"
  - "FAQ": "faq.md"
  - Api:
      - Erigon:
          - erigon_getHeaderByNumber: api/erigon/get-header-by-number.md
      - Ethereum: api/ethereum/eth-rpc.md
      - Otterscan:
          - ots_getApiLevel: api/otterscan/get-api-level.md
          - ots_getBlockDetails: api/otterscan/get-block-details.md
          - ots_getBlockDetailsByHash: api/otterscan/get-block-details-by-hash.md
          - ots_getBlockTransactions: api/otterscan/get-block-transactions.md
          - ots_hasCode: api/otterscan/has-code.md
      - Zilliqa:
          - CreateTransaction: api/zilliqa/api-transaction-create-tx.md
          - GetSmartContractState: api/zilliqa/api-contract-get-smartcontract-state.md
          - GetTransaction: api/zilliqa/api-transaction-get-tx.md
          - GetBalance: api/zilliqa/api-account-get-balance.md
          - GetCurrentMiniEpoch: api/zilliqa/api-blockchain-get-current-mini-epoch.md
          - GetLatestTxBlock: api/zilliqa/api-blockchain-get-latest-tx-block.md
          - GetMinimumGasPrice: api/zilliqa/api-transaction-get-minimum-gas-price.md
          - GetNetworkId: api/zilliqa/api-blockchain-get-network-id.md
          - GetVersion: api/zilliqa/api-blockchain-get-software-version.md
  - Ecosystem:
      - "Links": "ecosystem/ecosystem.md"
      - "Oracles": "ecosystem/chainlink.md"
      - "Wrapped ZIL": "ecosystem/wzil.md"
  - Running:
      - "Nodes": "running/node.md"
      - "Validators": "running/validator.md"
      - "Networks": "running/network.md"
  - "SDKs and tools": "sdk.md"
  - EVM:
      - Interop: zilevm/interop.md
      - Metamask: zilevm/metamask.md
      - Tools:
          - Hardhat: zilevm/tools/hardhat.md
          - OpenZeppelin: zilevm/tools/openzeppelin.md
          - RemixIDE: zilevm/tools/remix.md
          - "VSCode Plugins": zilevm/tools/vsc-plugins.md
  - Ziliqa:
      - "Native API": zilliqa/zilliqa.md
      - "Introduction": zilliqa/introduction-videos.md

theme:
  name: material
  logo: assets/zilliqa.png
  font:
    text: Poppins
  custom_dir: overrides/
  palette:
    scheme: zilliqa
  features:
    - content.code.annotate
    - navigation.indexes

markdown_extensions:
  - attr_list
  - md_in_html
  - markdown.extensions.toc:
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {
              kwds: { mode: generic, tag: pre },
            }
  # TODO: See https://github.com/facelessuser/pymdown-extensions
  #        - name: md-render
  #          class: md-render
  #          format: !!python/name:tools.pymdownx_md_render.md_sub_render
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {
              kwds: { mode: generic },
            }
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
      generic: true
      block_tag: "pre"
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path:
        - docs/.snippets
        - LICENSE.md
      #      auto_append:
      #      - refs.md
      check_paths: true
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.saneheaders:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zilliqa
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/XMRE9tt
    - icon: fontawesome/brands/telegram
      link: https://t.me/ZilliqaDevs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zilliqa
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCvinnFbf0u71cajoxKcfZIQ
    - icon: octicons/server-16
      link: https://status.zilliqa.com

plugins:
  - search
