apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml

patches:
  - target:
      kind: Ingress
      name: neo-savant-ide
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: ide.zilliqa.com
      - op: remove
        path: "/spec/rules/1"
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.global-static-ip-name: ide-zilliqa-com
          networking.gke.io/managed-certificates: neo-savant-ide
          kubernetes.io/ingress.class: gce

namespace: neo-savant-ide-prd
