apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdt-listen
  namespace: pdt
  labels:
    "app.kubernetes.io/name": "pdt-listen"
spec:
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": "pdt-listen"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "pdt-listen"
    spec:
      serviceAccountName: default
      containers:
        - image: pdt
          name: pdt-listen
          env:
            - name: PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: pdt
                  key: PROJECT_ID
            - name: DATASET_ID
              valueFrom:
                configMapKeyRef:
                  name: pdt
                  key: DATASET_ID
            - name: NETWORK_TYPE
              valueFrom:
                configMapKeyRef:
                  name: pdt
                  key: NETWORK_TYPE
          command: ["/bin/bash", "-c"]
          args:
            - ./pdt --network-type $NETWORK_TYPE bqlisten --project-id $PROJECT_ID --dataset-id $DATASET_ID,
