apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdt-pvc
  namespace: pdt
  labels:
    "app.kubernetes.io/name": "pdt"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: standard
