apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdt-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: standard
  volumeName: pdt-pv
