# bootstrap_address = [
#   "12D3KooWESbrSPohuw87dQDbJCB8qeeNgJsFD3ahkea3cu41m7bG",
#   "/ip4/172.16.8.135/tcp/3333",
# ]

# BSC Testnet
[[chain_configs]]
chain_gateway_block_deployed = 36696045
rpc_url = "https://bsc-prebsc-dataseed.bnbchain.org"
validator_manager_address = "0x43Eca260173De3cF0A2a68a5b3477C420f816F47"
chain_gateway_address = "0x72B9B59e48779A8b64554A3e2bC8b5297A04c68a"

# BSC Mainnet
# [[chain_configs]]
# chain_gateway_block_deployed = 0
# rpc_url = "https://binance.llamarpc.com"
# validator_manager_address = "0x5EDE85Ee7B2b4aefA88505Aa3893c1628FCeB0CE"
# chain_gateway_address = "0x2114e979b7CFDd8b358502e00f50Fd5f7787Fe63"

# [[chain_configs]]
# rpc_url = "http://localhost:8545"
# validator_manager_address = "0x4a50E1Be218279ca980EAb216d95E0A48B5aE872"
# chain_gateway_address = "0x4212b368876a54F99c741C8B5b64be2e52a6956b"

# [[chain_configs]]
# rpc_url = "http://localhost:8546"
# validator_manager_address = "0x4a50E1Be218279ca980EAb216d95E0A48B5aE8https://bsc.blockpi.network/v1/rpc/public72"
# chain_gateway_address = "0x4212b368876a54F99c741C8B5b64be2e52a6956b"

# Zilliqa Testnet
[[chain_configs]]
chain_gateway_block_deployed = 6542681
rpc_url = "https://dev-api.zilliqa.com"
validator_manager_address = "0x28E0D96C5B0Fd26654bd5b29ccDf77BE60D8bc1F"
chain_gateway_address = "0x10917A34FE60eE8364a401a6b1d3adaf80D84eb6"
block_instant_finality = true
legacy_gas_estimation = true

# Zilliqa Mainnet
# [[chain_configs]]
# chain_gateway_block_deployed = 0
# rpc_url = "https://api.zilliqa.com"
# validator_manager_address = "0xF391A1Ee7b3ccad9a9451D2B7460Ac646F899f23"
# chain_gateway_address = "0xE76669e1cCc150194eB92581baE79Ef6fa0E248E"
# block_instant_finality = true
# legacy_gas_estimation = true
