apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-validator-node0
  namespace: bridge-validator
  labels:
    "app.kubernetes.io/name": "validator-node0"
spec:
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": "validator-node0"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "validator-node0"
    spec:
      containers:
        - image: zilliqa-bridge-validator
          name: validator-node0
          envFrom:
            - secretRef:
                name: zilliqa-bridge-validator-secret
          command: ["/bin/bash", "-c"]
          args:
            - ./bridge-validator $PRIVATE_KEY --config-file /etc/bridge/config.toml --is-leader
          volumeMounts:
            - name: config-volume
              mountPath: /etc/bridge/config.toml
              subPath: config-leader.toml
      volumes:
        - name: config-volume
          configMap:
            name: zilliqa-bridge-validator-leader-config
