apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-secrets.yaml
  - deployment.yaml

configMapGenerator:
  - name: zilliqa-bridge-validator-config
    files:
      - config.toml
  - name: zilliqa-bridge-validator-leader-config
    files:
      - config-leader.toml
