apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml
  - frontend-config.yaml

patches:
  - target:
      kind: Ingress
      name: devex
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: devex.zilliqa.com
      - op: remove
        path: "/spec/rules/1"
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: devex-zilliqa-com
          networking.gke.io/managed-certificates: devex
          networking.gke.io/v1beta1.FrontendConfig: devex

namespace: devex-prd
