apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: multisig
  namespace: multisig
  labels:
    app.kubernetes.io/name: multisig
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        requestPath: /
        port: 80
  targetRef:
    group: ""
    kind: Service
    name: multisig
