name: "CI for Product Bridge"

on:
  push:
    paths:
      - products/bridge/**
      - ".github/workflows/**"

jobs:
  testing:
    runs-on: ubuntu-latest
    name: "Bridge Tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install nodes packages
        run: npm ci
        working-directory: products/bridge/bridge-web

      - name: Check bridge-web build
        run: npm run build
        working-directory: products/bridge/bridge-web

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Foundry tests
        run: forge test
        working-directory: products/bridge/smart-contracts
