name: "CI for Product Bridge"

on:
  push:
    paths:
      - products/bridge/**
      - ".github/workflows/**"

jobs:
  testing:
    runs-on: ubuntu-latest
    name: "Bridge Tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        working-directory: products/bridge/smart-contracts

      - name: Run Hardhat tests
        run: pnpm test
        working-directory: products/bridge/smart-contracts

      - name: Run Foundry tests
        run: pnpm test:foundry
        working-directory: products/bridge/smart-contracts
