name: "CICD"

on:
  # Test run before merging
  pull_request:
    branches:
      - main
  # On merged
  push:
    branches:
      - main
  # On released
  release:
    types: [created]

jobs:
  build-docker:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-22.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: "Build and push images"
    strategy:
      fail-fast: false
      matrix:
        application: [neo-savant]
        include:
          - application: neo-savant
            docker_domain: asia-docker.pkg.dev
            registry_stg: asia-docker.pkg.dev/prj-d-devops-services-4dgwlsse/zilliqa-private
            image_name: neo-savant
            path: products/neo-savant
    env:
      DEFAULT_BRANCH: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.GCP_PRD_GITHUB_WIF }}"
          service_account: "${{ secrets.GCP_PRD_GITHUB_SA_GCS_CACHE }}"
          create_credentials_file: true

      - name: Configure bazel GCS cache
        run: |
          export BAZEL_REMOTE_CACHE_CREDENTIALS_JSON='${{ steps.auth.outputs.credentials_file_path }}'
          export BAZEL_REMOTE_CACHE_ENDPOINT='${{ vars.BAZEL_REMOTE_CACHE_ENDPOINT }}'
          python config/gcp_cs_cache.py
        shell: bash

      - name: Preparing merged branches
        # Fetch the ref of the base branch, just the single commit.
        run: |
          git config --global user.email "bot@zilliqa.com"
          git config --global user.name "Zilliqa Bot"

          echo "Running git checkout ${{ env.DEFAULT_BRANCH }}"

          git checkout ${{ env.DEFAULT_BRANCH }}
          git fetch --all --tags
          git pull --all

          # Checking out the base branch to make this our working branch and
          # merge the head
          echo "Running git checkout ${{ github.base_ref }}"

          git checkout ${{ github.base_ref }}
          git fetch --all --tags
          git pull --all
          python config/workspace-status.py

      - name: Committing head
        if: github.event_name == 'pull_request'
        env:
          HEAD_REF: ${{ github.head_ref }}
        # Fetch the ref of the base branch, just the single commit.
        run: |
          echo "Running git merge --squash ${{ env.HEAD_REF }}"
          git merge --squash ${{ env.HEAD_REF }}

          git add . -A
          git commit -m "Finish merge"
          python config/workspace-status.py

      - name: "Authenticate to Google Cloud - staging"
        if: github.ref_name == env.DEFAULT_BRANCH && github.event_name != 'release'
        id: auth_docker
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.GCP_PRD_GITHUB_WIF }}"
          service_account: "${{ secrets.GCP_STG_GITHUB_SA_DOCKER_REGISTRY }}"
          create_credentials_file: true

      - name: Login to the registry - staging
        if: github.ref_name == env.DEFAULT_BRANCH && github.event_name != 'release'
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.docker_domain }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth_docker.outputs.access_token }}"

      - name: Get tag version staging - staging
        if: github.event_name != 'release'
        id: set-tag
        uses: Zilliqa/gh-actions-workflows/actions/generate-tag@v1
        with:
          tag: ${{ matrix.registry_stg }}/${{ matrix.image_name }}
          length: 8

      - name: "Build ${{ matrix.application }} - staging"
        if: github.event_name != 'release'
        env:
          ENVIRONMENT: stg
          IMAGE_TAG: ${{ steps.set-tag.outputs.tags }}
        run: |
          cd ${{ matrix.path }}
          make image/build

      - name: "Push ${{ matrix.application }} - staging"
        if: github.ref_name == env.DEFAULT_BRANCH && github.event_name != 'release'
        env:
          ENVIRONMENT: stg
          IMAGE_TAG: ${{ steps.set-tag.outputs.tags }}
        run: |
          cd ${{ matrix.path }}
          make image/push
